# Generated by Django 5.1.2 on 2024-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SECURITY_REFERANT', 'Security referent'), ('GUEST', 'Guest')], max_length=30),
        ),
    ]
