# Generated by Django 5.1.2 on 2024-11-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='email', max_length=10)),
                ('mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('payloads_sent', models.PositiveIntegerField(default=0)),
                ('has_clicked', models.PositiveIntegerField(default=0)),
                ('has_been_signaled', models.PositiveIntegerField(default=0)),
                ('arbitrary_failures', models.PositiveIntegerField(default=0)),
                ('duration_of_campaign', models.DurationField(help_text='Duration of the campaign in days, hours, and minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='shared_models.client')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='shared_models.client')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_of_work', to='shared_models.client')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='shared_models.client')),
                ('interests', models.ManyToManyField(blank=True, to='shared_models.interest')),
                ('place_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared_models.placeofwork')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('has_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='Timestamp of when the message was clicked', null=True)),
                ('has_been_signaled', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(default='Pending', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared_models.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared_models.target')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='targets',
            field=models.ManyToManyField(related_name='campaigns', to='shared_models.target'),
        ),
    ]
