# Generated by Django 5.1.2 on 2024-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='url_id',
            field=models.TextField(default='07rq-5g8-wpc-4oe-zhs6', max_length=21),
            preserve_default=False,
        ),
    ]
