# Generated by Django 5.1.2 on 2024-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_campaign_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='url_id',
            field=models.CharField(max_length=21),
        ),
    ]
