# Generated by Django 5.1.2 on 2024-11-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_alter_campaign_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='target',
            name='places_of_work',
            field=models.ManyToManyField(blank=True, related_name='targets', to='shared_models.placeofwork'),
        ),
    ]
