# Generated by Django 5.1.2 on 2024-11-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_remove_target_place_of_work_target_places_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
