# Generated by Django 5.1.2 on 2024-11-01 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_campaign_has_opened_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(null=True, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
