# Generated by Django 5.1.2 on 2024-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0008_alter_client_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='client',
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ManyToManyField(related_name='campaigns', to='shared_models.client'),
        ),
    ]
