# Generated by Django 5.1.2 on 2024-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0009_remove_campaign_client_campaign_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
