# Generated by Django 5.1.2 on 2024-11-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0010_campaign_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='client',
            new_name='clients',
        ),
    ]
