# Generated by Django 5.1.2 on 2024-11-02 22:20

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0011_rename_client_campaign_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
