# Generated by Django 5.1.2 on 2024-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0012_target_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=40),
        ),
    ]
