# Generated by Django 5.1.2 on 2024-11-03 15:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_alter_message_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='target',
            name='country',
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='target',
            name='lastname',
            field=models.CharField(default='lastname', max_length=255),
            preserve_default=False,
        ),
    ]
