# Generated by Django 5.1.2 on 2024-11-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0014_rename_name_target_firstname_remove_target_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='users',
        ),
    ]
