# Generated by Django 5.1.2 on 2024-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_remove_client_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='has_clicked',
            new_name='has_been_clicked',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='has_been_signaled',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='has_clicked',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='has_opened_attachments',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='payloads_sent',
        ),
        migrations.AddField(
            model_name='interest',
            name='z_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='attachments_opened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the attachments have been opened', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_opened_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='signaled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the message was signaled', null=True),
        ),
    ]
