# Generated by Django 5.1.2 on 2024-11-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0016_rename_has_clicked_message_has_been_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(auto_now=True, help_text='Start date of the campaign'),
        ),
    ]
