# Generated by Django 5.1.2 on 2024-11-05 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0017_campaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start date of the campaign'),
        ),
    ]
