# Generated by Django 5.1.2 on 2024-11-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0020_job_alter_target_job_category_delete_jobcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='shared_models.client')),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.jobtype'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
