# Generated by Django 5.1.2 on 2024-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0021_jobtype_alter_target_job_category_delete_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='job_category',
            new_name='job_type',
        ),
    ]
