# Generated by Django 5.1.2 on 2024-11-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0022_rename_job_category_target_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='places_of_work',
        ),
        migrations.AddField(
            model_name='target',
            name='places_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.placeofwork'),
        ),
    ]
