# Generated by Django 5.1.2 on 2024-11-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0023_remove_target_places_of_work_target_places_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='z_index',
        ),
        migrations.AddField(
            model_name='message',
            name='creds_filled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user credentials have been filled on the fake website', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_creds_filled',
            field=models.BooleanField(default=False),
        ),
    ]
