# Generated by Django 5.1.2 on 2024-11-10 22:22

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0024_remove_interest_z_index_message_creds_filled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='compromise_type',
            field=models.CharField(choices=[('click', 'User has clicked on the malicious link'), ('download_attachements', 'User has downloaded the attachements'), ('open_attachements', 'User has opened the attachements'), ('credentials_leak', 'User has leaked some credentials')], default='click', help_text='When is a target considered compromised?', max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='target',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='job_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.jobtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='places_of_work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.placeofwork'),
            preserve_default=False,
        ),
    ]
