# Generated by Django 5.1.2 on 2024-11-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_campaign_compromise_type_alter_client_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='has_opened_attachments',
            new_name='has_downloaded_attachments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments_opened_at',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the attachments have been downloaded', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='compromise_type',
            field=models.CharField(choices=[('click', 'User has clicked on the malicious link'), ('download_attachements', 'User has downloaded the attachments'), ('open_attachements', 'User has opened the attachments'), ('credentials_leak', 'User has leaked some credentials')], default='click', help_text='When is a target considered compromised?', max_length=25),
        ),
    ]
