# Generated by Django 5.1.2 on 2024-11-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0026_rename_has_opened_attachments_message_has_downloaded_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments_opened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the attachments have been opened', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_opened_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
