# Generated by Django 5.1.2 on 2024-11-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0027_message_attachments_opened_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creds_filled_at',
            new_name='creds_leak_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='has_creds_filled',
            new_name='has_creds_leak',
        ),
    ]
