# Generated by Django 5.1.2 on 2024-11-11 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_rename_creds_filled_at_message_creds_leak_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='duration_of_campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='End date of the campaign'),
        ),
    ]
