# Generated by Django 5.1.2 on 2024-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0029_remove_campaign_duration_of_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('download_attachements', 'Download attachment'), ('open_attachements', 'Open attachment'), ('credentials_leak', 'Credentials leak'), ('report', 'Report')], help_text='Type of event triggered', max_length=30)),
                ('event_date', models.DateTimeField(blank=True, help_text='Timestamp of when the event have been triggered', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments_downloaded_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments_opened_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='clicked_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creds_leak_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_been_clicked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_been_signaled',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_creds_leak',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_downloaded_attachments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_opened_attachments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='signaled_at',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=None, help_text='End date of the campaign'),
        ),
        migrations.AddField(
            model_name='message',
            name='events',
            field=models.ManyToManyField(related_name='messages', to='shared_models.messagelog'),
        ),
    ]
