# Generated by Django 5.1.2 on 2024-11-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0030_messagelog_remove_message_attachments_downloaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='messagelog',
            old_name='event_type',
            new_name='type',
        ),
    ]
