# Generated by Django 5.1.2 on 2024-11-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0031_rename_event_date_messagelog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='events',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='messages',
            field=models.ManyToManyField(related_name='events', to='shared_models.message'),
        ),
    ]
