# Generated by Django 5.1.2 on 2024-11-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0032_remove_message_events_messagelog_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='messages',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shared_models.message'),
        ),
    ]
