# Generated by Django 5.1.2 on 2024-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0033_remove_messagelog_messages_messagelog_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='messages',
            new_name='message',
        ),
    ]
