# Generated by Django 5.1.2 on 2024-11-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0034_rename_messages_messagelog_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('click', 'Click'), ('download_attachements', 'Download attachment'), ('open_attachements', 'Open attachment'), ('credentials_leak', 'Credentials leak'), ('report', 'Report')], help_text='Type of event triggered', max_length=30)),
                ('date', models.DateTimeField(blank=True, help_text='Timestamp of when the event have been triggered', null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shared_models.message')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
