# Generated by Django 5.1.2 on 2024-11-11 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0035_eventslog_delete_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='expected_signaling',
            field=models.PositiveSmallIntegerField(default=20, help_text='Expected signaling for this campain. Enter a percentage value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
