# Generated by Django 5.1.2 on 2024-11-18 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0036_campaign_expected_signaling'),
    ]

    operations = [
    ]
