# Generated by Django 5.1.2 on 2024-11-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0037_feedbacklog'),
    ]

    operations = [
    ]
