# Generated by Django 5.1.2 on 2024-11-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0038_rename_feedbacklog_feedbackslog'),
    ]

    operations = [
    ]
