# Generated by Django 5.1.2 on 2024-11-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0039_feedbackstype_feedbackslog_feedback_type'),
    ]

    operations = [
    ]
