# Generated by Django 5.1.2 on 2024-11-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0041_cognitivebiases_remove_feedbackstype_campaign_and_more'),
    ]

    operations = [
    ]
