# Generated by Django 5.1.2 on 2024-11-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0042_remove_feedbackstype_client_delete_feedbackslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_types', to='shared_models.client')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbacksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback', to='shared_models.message')),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks_logs', to='shared_models.feedbackstype')),
            ],
        ),
    ]
