# Generated by Django 5.1.2 on 2024-11-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0043_feedbackstype_feedbackslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstype',
            name='label',
            field=models.CharField(default='bite', max_length=255),
            preserve_default=False,
        ),
    ]
