# Generated by Django 5.1.2 on 2024-11-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0044_feedbackstype_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_categories', to='shared_models.client')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackstype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks_types', to='shared_models.feedbackscategory'),
        ),
    ]
