# Generated by Django 5.1.2 on 2024-11-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0045_feedbackscategory_feedbackstype_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackslog',
            old_name='feedback',
            new_name='feedback_message',
        ),
        migrations.RemoveField(
            model_name='feedbackscategory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='feedbackstype',
            name='client',
        ),
    ]
