# Generated by Django 5.1.2 on 2024-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0046_rename_feedback_feedbackslog_feedback_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackslog',
            name='feedback_type',
        ),
        migrations.AddField(
            model_name='feedbackslog',
            name='feedback_type',
            field=models.ManyToManyField(blank=True, related_name='feedbacks_logs', to='shared_models.feedbackstype'),
        ),
    ]
