# Generated by Django 5.1.2 on 2024-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0047_remove_feedbackslog_feedback_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackscategory',
            name='view_call',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
