# Generated by Django 5.1.2 on 2024-11-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0048_feedbackscategory_view_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackscategory',
            old_name='view_call',
            new_name='view_class',
        ),
    ]
