# Generated by Django 5.1.2 on 2024-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0049_rename_view_call_feedbackscategory_view_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackscategory',
            name='view_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackscategory',
            name='view_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
