# Generated by Django 5.1.2 on 2024-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0051_campaign_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='email', max_length=10),
        ),
    ]
