# Generated by Django 5.1.2 on 2025-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0053_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#5092B6', max_length=10),
        ),
    ]
