# Generated by Django 5.1.2 on 2025-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0054_alter_campaign_type_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#3F1F02', max_length=10),
        ),
    ]
