# Generated by Django 5.1.2 on 2025-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0055_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#9CC1B1', max_length=10),
        ),
    ]
