# Generated by Django 5.1.2 on 2025-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0056_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#E3E809', max_length=10),
        ),
    ]
