# Generated by Django 5.1.2 on 2025-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0057_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#598954', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='targets', to='shared_models.interest'),
        ),
    ]
