# Generated by Django 5.1.2 on 2025-01-21 20:04

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0058_alter_interest_color_alter_target_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfWorkCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#1913F0', max_length=10),
        ),
        migrations.CreateModel(
            name='TargetCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='targets', to='shared_models.interestcopy')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.jobtypecopy')),
                ('places_of_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.placeofworkcopy')),
            ],
        ),
    ]
