# Generated by Django 5.1.2 on 2025-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0059_interestcopy_jobtypecopy_placeofworkcopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#89F743', max_length=10),
        ),
    ]
