# Generated by Django 5.1.2 on 2025-01-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0060_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#BC1D39', max_length=10),
        ),
    ]
