# Generated by Django 5.1.2 on 2025-01-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0061_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#298515', max_length=10),
        ),
        migrations.AlterField(
            model_name='targetcopy',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='shared_models.jobtypecopy'),
        ),
        migrations.AlterField(
            model_name='targetcopy',
            name='places_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='shared_models.placeofworkcopy'),
        ),
    ]
