# Generated by Django 5.1.2 on 2025-01-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0062_alter_interest_color_alter_targetcopy_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#A9F4A4', max_length=10),
        ),
    ]
