# Generated by Django 5.1.2 on 2025-01-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0063_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#050DF3', max_length=10),
        ),
    ]
