# Generated by Django 5.1.2 on 2025-01-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0064_alter_interest_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='targets',
        ),
        migrations.AddField(
            model_name='interestcopy',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='shared_models.campaign'),
        ),
        migrations.AddField(
            model_name='jobtypecopy',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='shared_models.campaign'),
        ),
        migrations.AddField(
            model_name='placeofworkcopy',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places_of_work', to='shared_models.campaign'),
        ),
        migrations.AddField(
            model_name='targetcopy',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='shared_models.campaign'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#7D0749', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared_models.targetcopy'),
        ),
    ]
