# Generated by Django 5.1.2 on 2025-01-23 15:58

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0065_remove_campaign_targets_interestcopy_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#4E5D67', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.jobtype'),
        ),
        migrations.AlterField(
            model_name='target',
            name='places_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='shared_models.placeofwork'),
        ),
    ]
