# Generated by Django 5.1.2 on 2025-04-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0066_target_country_alter_interest_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#7EC2D1', max_length=10),
        ),
    ]
