# Generated by Django 5.1.2 on 2025-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0067_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#DA8C36', max_length=10),
        ),
    ]
