# Generated by Django 5.1.2 on 2025-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0068_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#A2DCCA', max_length=10),
        ),
    ]
