# Generated by Django 5.1.2 on 2025-04-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0069_alter_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='url_id',
            field=models.CharField(max_length=21, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#CF688E', max_length=10),
        ),
    ]
