# Generated by Django 5.1.2 on 2025-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0070_alter_campaign_url_id_alter_interest_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#31C078', max_length=10),
        ),
    ]
